data:
  train_files: /scratch/high_modality/geom_train.jsonl
  val_files: /scratch/high_modality/geom_valid_mini.jsonl
  prompt_key: problem
  answer_key: answer
  image_key: images
  max_prompt_length: 6140
  max_response_length: 2048
  rollout_batch_size: 512
  shuffle: true
  seed: 1
  max_pixels: 524288
  min_pixels: 32768

algorithm:
  adv_estimator: reinforce_plus_plus
  kl_coef: 0.0

worker:
  actor:
    global_batch_size: 128
    micro_batch_size_per_device_for_update: 2
    micro_batch_size_per_device_for_experience: 8
    max_grad_norm: 10.0
    use_kl_loss: true
    kl_loss_coef: 1.0e-3
    kl_loss_type: low_var_kl
    padding_free: true
    ulysses_sequence_parallel_size: 1
    model:
      model_path: Qwen/Qwen2.5-7B-Instruct
      enable_gradient_checkpointing: true
      trust_remote_code: false
      freeze_vision_tower: false
    optim:
      lr: 5.0e-6
      betas: [0.9, 0.95]
      weight_decay: 1.0e-2
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
    offload:
      offload_params: true
      offload_optimizer: true

  rollout:
    temperature: 1.0
    n: 5
    gpu_memory_utilization: 0.3
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_parallel_size: 2
    limit_images: 0
    val_override_config:
      temperature: 0.5
      n: 1

  ref:
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: true
      enable_rank0_init: true
    offload:
      offload_params: false

  reward:
    reward_type: function
    compute_score: medical

trainer:
  total_episodes: 15
  logger: ["console", "wandb"]
  project_name: easy_r1
  experiment_name: qwen2_5_7b_math
  n_gpus_per_node: 4
  nnodes: 1
  val_freq: 200
  val_before_train: false
  val_only: false
  val_generations_to_log: 1
  save_freq: 200
  remove_previous_ckpt: false
  remove_ckpt_after_load: false
  save_checkpoint_path: null
  load_checkpoint_path: null
